### ISSUE TITLE
Java : Library search - R&D

### ISSUE THREAD

**Issue by PavanAjit** [SE-spring2021/Html_to_pdf#4]
Research existing libraries that can be used in the application for webpage scraping and HTML to PDF conversion.

**Comment by sassani** [comment]
Please add your data to the provided datasheet [here](https://docs.google.com/spreadsheets/d/1Kmaifo4cP-Vg-sDst21fn3SXtCkLZBQNcD48d5dF9ZA/edit?usp=sharing).
