### ISSUE TITLE
Python: Library Search - R&D

### ISSUE THREAD

**Issue by PavanAjit** [SE-spring2021/Html_to_pdf#5]
Research existing libraries that can be used in the application for webpage scraping and HTML to PDF conversion.

**Comment by PavanAjit** [comment]
### Python Libraries
#### Libraries for converting webpage to PDF:

1. [pdfkit](https://pypi.org/project/pdfkit/#description)
Source Code: https://github.com/JazzCore/python-pdfkit
Stars: 1.4k
LSRD: Jan 9 2017
Age: 4+ years
Issues: 85
NC: 21
Used by: 3.6k
Dependency: [wkhtmlpdf](https://wkhtmltopdf.org/) : Requires downloading binaries to client machine. Alternately, source code can be packaged from [github source](https://github.com/wkhtmltopdf/wkhtmltopdf) and installed on client machine. Executable need to be added to system path post installation.

2. [WeasyPrint](https://weasyprint.org/)
Source Code: https://github.com/Kozea/WeasyPrint
Stars: 4.1k
LSRD: Dec 6 2020
Age: 9+ years
Issues: 140
NC: 89
Used by: N/A

3. [xhtml2pdf](https://xhtml2pdf.readthedocs.io/en/latest/index.html#)
Source Code: https://github.com/xhtml2pdf/xhtml2pdf
Stars: 1.7k
LSRD: Jan 21 2020
Age: 13+ years
Issues: 100
NC: 112
Used by: 4.2k

Others:

- [pdfcrowd](https://pdfcrowd.com/doc/api/html-to-pdf/python/) --> Paid library

#### Libraries for scraping webpage to extract URLs from a webpage for PDF conversion (drill down levels):
##### To fetch HTML/XML from webpages:
1. [requests](https://pypi.org/project/requests/)
Source Code: https://github.com/psf/requests
Stars: 44.6k
LSRD: Dec 16 2020
Age: 10+ years
Issues: 245
NC: 603
Used by: 814k
Use case: Static Webpages

2. [Selenium](https://selenium-python.readthedocs.io/#)
Source Code: https://github.com/SeleniumHQ/selenium
Stars: 19.9k
LSRD: Dec 19 2018
Age: 14+ years
Issues: 223
NC: 558
Used by: 84.7k
Use case: Dynamic Webpages

##### To parse HTML/XML content into useful data
1. [BeautifulSoup](https://www.crummy.com/software/BeautifulSoup/)
Source Code : https://bazaar.launchpad.net/~leonardr/beautifulsoup/bs4/files
Stars: N/A
LSRD: Oct 3 2020
Age: 9+ years
Issues: N/A
NC: 20
Used by: N/A

2. [lxml](https://lxml.de/)
Source Code : https://github.com/lxml/lxml
Stars: 1.8k
LSRD: Nov 27 2020
Age: 15+ years
Issues: N/A
NC: 111
Used by: 150k

**Comment by sassani** [comment]
Please add your data to the provided datasheet [here](https://docs.google.com/spreadsheets/d/1Kmaifo4cP-Vg-sDst21fn3SXtCkLZBQNcD48d5dF9ZA/edit?usp=sharing).

**Comment by PavanAjit** [comment]
Note: Selenium is a standalone Web scraper and Parser. Wouldn't need an additional library to be installed for parsing html/web data.
