### ISSUE TITLE
Gather Application Requirements

### ISSUE THREAD

**Issue by PavanAjit** [SE-spring2021/Html_to_pdf#7]
Put together requirements for developing the application.

**Comment by sassani** [comment]
Requirements

Functional:
    1. User can put any URL.
    2. User can define digging level (minimum 3)
    3. User can define the text format (font and size)
    4. System shall fetch data automatically from the web according to the number of levels which is provided by the user.
    5. The first web page on the given URL is level 1.
    6. System shall convert web pages to a pdf file and create an external link for all hyperlinks on the page.
    7. User can save the produced pdf file with any name.
        
Nonfunctional:
    1. Runtime complexity
    2. Memory complexity
    3. Language and libraries
